export const authTypes = {
  LOGIN_AUTHENTICATION: 'LOGIN_AUTHENTICATION',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_ERROR: 'LOGIN_ERROR',

  LOG_OUT: 'LOGOUT'
};

export const newsTypes = {
  GET_TOP_HEADLINES_BY_COUNTRY: ' GET_TOP_HEADLINES_BY_COUNTRY',
  GET_EVERYTHING: 'GET_EVERYTHING',
  GET_USER_PROFILE: 'GET_USER_PROFILE'
};
