export const authTypes = {
  LOGIN_AUTHENTICATED: 'LOGIN_AUTHENTICATED',
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_ERROR: 'LOGIN_ERROR',

  LOG_OUT: 'LOGOUT'
};

export const newsTypes = {
  GET_TOP_HEADLINES_BY_COUNTRY: ' GET_TOP_HEADLINES_BY_COUNTRY',
  GET_EVERYTHING: 'GET_EVERYTHING',
  GET_STORY: 'GET_STORY',
  GET_PROFILE: 'GET_PROFILE',
  UPDATE_PROFILE: 'UPDATE_PROFILE'
};

export const alertType = {
  ALERT_ERROR_SHOW: 'ALERT_ERROR_SHOW',
  ALERT_ERROR_REMOVE: 'ALERT_ERROR_REMOVE'
};
